### ISSUE TITLE
Print long picture the printer print not success and not cutting paper. Please help me to solve this problem

### ISSUE THREAD

**Issue by ul-rotha** [andrey-ushakov/esc_pos_printer#91]

**Comment by andrey-ushakov** [comment]
Hi there,

A new version was published today. It should resolve the issue.
Feel free to reopen the issue if need

**Comment by ul-rotha** [comment]
> Hi there,
> 
> A new version was published today. It should resolve the issue.
> Feel free to reopen the issue if need

it's still the same problem. i capture long widget as receipt pos image. then send image to printer. it can not print successfully. can print 50% height of image.

**Comment by YouSour** [comment]
@ul-rotha hi, did you solve this problem, yet ?
